[project]
name = "hash-emit"
authors = ["HashEmit Team"]
description = "Decentralized hash tracking and event management platform"
telemetry = false
requirements = []
[contracts.hash-emit-access]
path = "contracts/hash-emit-access.clar"
depends_on = []

[contracts.hash-emit-core]
path = "contracts/hash-emit-core.clar"
depends_on = []

[contracts.hash-emit-integrity]
path = "contracts/hash-emit-integrity.clar"
depends_on = []

[contracts.hash-emit-metadata]
path = "contracts/hash-emit-metadata.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
